// import Navbar from "@/components/Navbar";
// import Sidebar from "@/components/Sidebar";
// import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased p-8`}
//       >
//         <Navbar /> {/* Navbar component correctly placed here */}
//         <div className="flex pt-4 gap-4">
//           <div className="w-[20%]">
//             <Sidebar />
//           </div>
//           <div className="w-[80%] bg-[#F0F4F9]">{children}</div>
//         </div>
//       </body>
//     </html>
//   );
// }

// "use client";
// import { useEffect } from "react";
// import useAuthStore from "@/lib/store/authStore";
// import Navbar from "@/components/Navbar";
// import Sidebar from "@/components/Sidebar";
// import RouteProtector from "@/lib/routeProtector";
// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Control Panel",
//   description: "Admin dashboard",
// };

// export default function ControlPanelLayout({ children }) {
//   const refreshAccessToken = useAuthStore((state) => state.refreshAccessToken);

//   useEffect(() => {
//     refreshAccessToken();
//   }, [refreshAccessToken]);

//   return (
//     <RouteProtector>
//       <div className={`${geistSans.variable} ${geistMono.variable} antialiased p-8`}>
//         <Navbar />
//         <div className="flex pt-4 gap-4">
//           <div className="w-[20%]">
//             <Sidebar />
//           </div>
//           <div className="w-[80%] bg-[#F0F4F9] p-6 rounded-lg shadow-md">{children}</div>
//         </div>
//       </div>
//     </RouteProtector>
//   );
// }

// "use client";
// import Navbar from "@/components/Navbar";
// import Sidebar from "@/components/Sidebar";
// import RouteProtector from "@/lib/routeProtector"; // Protect routes
// import useAuthStore from "@/lib/store/authStore";
// import { useEffect } from "react";

// export default function ControlPanelLayout({ children }) {
//   const refreshAccessToken = useAuthStore((state) => state.refreshAccessToken);

//   useEffect(() => {
//     refreshAccessToken(); // 🔄 Refresh only when needed
//   }, []);

//   return (
//     <RouteProtector>
//       <div className="antialiased p-8">
//         <Navbar />
//         <div className="flex pt-4 gap-4">
//           <div className="w-[20%]">
//             <Sidebar />
//           </div>
//           <div className="w-[80%] bg-[#F0F4F9] p-6 rounded-lg shadow-md">{children}</div>
//         </div>
//       </div>
//     </RouteProtector>
//   );
// }

"use client";
import Navbar from "@/components/Navbar";
import { useEffect } from "react";
import Sidebar from "@/components/Sidebar";

import { useAuthStore } from "@/lib/store/authStore";
import RouteProtector from "@/components/RouteProtector";




export default function ControlPanelLayout({ children }) {

  return (
   

<div className="antialiased p-8">
        <Navbar />
        <div className="flex pt-4 gap-4">
          <div className="w-[20%]">
            <Sidebar />
          </div>
          <RouteProtector>
          <div className="w-[80%] bg-[#F0F4F9] p-6 rounded-lg shadow-md">{children}</div>
          </RouteProtector>
        </div>
      </div>


        
   
   
  );
}
